/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#bec8d2",
        "on-surface": "#dfe2f0",
        "inverse-surface": "#dfe2f0",
        "surface-container-low": "#171c25",
        "surface-container": "#1b2029",
        "tertiary": "#ffb95f",
        "on-secondary-fixed-variant": "#005048",
        "secondary-fixed": "#71f8e4",
        "surface-dim": "#0f131d",
        "primary-fixed": "#c9e6ff",
        "primary": "#89ceff",
        "secondary-fixed-dim": "#4fdbc8",
        "inverse-primary": "#006591",
        "on-tertiary-container": "#4a2c00",
        "surface-tint": "#89ceff",
        "on-error": "#690005",
        "surface": "#0f131d",
        "on-secondary": "#003731",
        "secondary-container": "#04b4a2",
        "error": "#ffb4ab",
        "secondary": "#4fdbc8",
        "error-container": "#93000a",
        "on-primary": "#00344d",
        "outline": "#88929b",
        "on-primary-fixed": "#001e2f",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#004c6e",
        "background": "#0f131d",
        "tertiary-fixed-dim": "#ffb95f",
        "outline-variant": "#3e4850",
        "on-secondary-fixed": "#00201c",
        "surface-container-lowest": "#0a0e17",
        "tertiary-container": "#d88a00",
        "primary-fixed-dim": "#89ceff",
        "on-tertiary-fixed-variant": "#653e00",
        "on-secondary-container": "#003f38",
        "inverse-on-surface": "#2c303b",
        "surface-container-highest": "#31353f",
        "surface-variant": "#31353f",
        "surface-bright": "#353944",
        "on-tertiary": "#472a00",
        "on-error-container": "#ffdad6",
        "on-background": "#dfe2f0",
        "surface-container-high": "#262a34",
        "on-tertiary-fixed": "#2a1700",
        "primary-container": "#0ea5e9",
        "on-primary-container": "#003751"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "syne": ["Syne", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
